export ES_JAVA_OPTS="-Xms512m -Xmx512m"

export ELASTIC_PASSWORD="changeme"
export LOGSTASH_INTERNAL_PASSWORD="changeme"
export KIBANA_SYSTEM_PASSWORD="changeme"
export METRICBEAT_INTERNAL_PASSWORD=""
export FILEBEAT_INTERNAL_PASSWORD=""
export HEARTBEAT_INTERNAL_PASSWORD=""
export MONITORING_INTERNAL_PASSWORD=""
export BEATS_SYSTEM_PASSWORD=""

